---
name: Build and Push Image to AWS ECR
on:
  push:
    branches: [ main ]
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-access-key-id: ${{ secrets.DHANYA_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.DHANYA_SECRET_KEY }}
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./image_tag_update.sh major
    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: custom-tools
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        echo $IMAGE_TAG
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Display pkg list
      id: get_versions
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: custom-tools
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        set -x
        echo "Installed software list"
        # docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo ":: set-output name=JAVA_VERSION::$(docker run $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG java -version)"
        echo "VERSION1=$(docker run $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG java -version)" >> $GITHUB_ENV
        # echo "java_version=${java_version}" >> $GITHUB_ENV
    - name: Software List
      run: |
        echo "Software Versions"
        echo "Java Version is: ${{ env.VERSION1 }}"
        echo "Java Version is: ${{ env.JAVA_VERSION }}"
        echo "Java Version is: ${{ steps.get_versions.outputs.java_version }}"
    
    - id: env-setup
      run: |
        {
          "env_token=$(docker run $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG java -version)"
          "env_domain=$(docker run $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG java -version)"
        } >> $GITHUB_OUTPUT

        {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| env_token  | $env_token  |"
          echo "| env_domain | $env_domain |"
        } >> $GITHUB_STEP_SUMMARY
    - run: |
        echo "${{ steps.env-setup.outputs.env_token }}"
        echo "${{ steps.env-setup.outputs.env_domain }}"